#debug: true
spring:
  config:
    import: "kubernetes:"
  cloud:
    kubernetes:
      reload:
        enabled: true
      config:
        enabled: true
        name: notification-service
        namespace: transaction-processing
        fail-fast: true
      enabled: true
  application:
        name: notification-service

