apiVersion: v1
kind: ConfigMap
metadata:
  name: settings
data:
  application.yaml: |-
    gemfire:
        sni:
            host: envoy-gemfire-gateway.tanzu-gemfire.svc.cluster.local
            port: 9000
    rabbitmq:
        queues: 5
        throughput: 2
    spring:
        data:
            gemfire:
                cache:
                    name: Customers
        rabbitmq:
            host: tanzu-rabbitmq.rabbitmq-system.svc.cluster.local
            password: admin
            port: 5672
            username: admin
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service
data:
  application.yaml: |-
    gemfire:
    sni:
        host: envoy-gemfire-gateway.tanzu-gemfire.svc.cluster.local
        port: 9000
    rabbitmq:
        queues: 5
        throughput: 2
    spring:
        data:
            gemfire:
                cache:
                    name: Customers
        rabbitmq:
            host: tanzu-rabbitmq.rabbitmq-system.svc.cluster.local
            password: admin
            port: 5672
            username: admin
  
