apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ .Release.Name }}
data:
  application.yaml: |-
    cache:
        host: envoy-gemfire-gateway.tanzu-gemfire.svc.cluster.local
        port: 9000
    rabbitmq:
        queues: 5
        throughput: 2
    spring:
        rabbitmq:
            host: tanzu-rabbitmq.rabbitmq-system.svc.cluster.local
            password: admin
            port: 5672
            username: admin
