apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ .Release.Name }}
data:
  application.yaml: |-
    cache:
        host: envoy-gemfire-gateway.tanzu-gemfire.svc.cluster.local
        port: 9000
    rabbitmq:
        queues: 5
        throughput: 2
    spring:
        data:
            gemfire:
                cache:
                    name: Customers
                management:
                    http:
                        host: gemfire-cluster-1-locator.tanzu-gemfire.svc.cluster.local
                pool:
                    locators: gemfire-cluster-1-locator-0.gemfire-cluster-locator.tanzu-gemfire.svc.cluster.local[10334],gemfire-cluster-1-locator-1.gemfire-cluster-locator.tanzu-gemfire.svc.cluster.local[10334]
                    #socket-factory-bean-name: myProxySocketFactory
                security:
                    ssl:
                        keystore: ./certs/keystore.p12
                        keystore.password: mo_CNyEBoRHRXrHJeJly3djfjfMq3CY8QmxnA8aK1Mw=
                        truststore: ./certs/truststore.p12
                        truststore.password: mo_CNyEBoRHRXrHJeJly3djfjfMq3CY8QmxnA8aK1Mw=
        rabbitmq:
            host: tanzu-rabbitmq.rabbitmq-system.svc.cluster.local
            password: admin
            port: 5672
            username: admin
