apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "notification-service.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "notification-service.name" . }}
    helm.sh/chart: {{ include "notification-service.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  serviceName: {{ include "notification-service.fullname" . }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "notification-service.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  # volumeClaimTemplates:
  # - metadata:
  #     name: data
  #     labels:
  #       app.kubernetes.io/name: {{ include "notification-service.name" . }}
  #       helm.sh/chart: {{ include "notification-service.chart" . }}
  #       app.kubernetes.io/instance: {{ .Release.Name }}
  #       app.kubernetes.io/managed-by: {{ .Release.Service }}
  #       # Revision should change with each helm upgrade, so if we use it here
  #       # and don't specify spec.selector, we run into https://github.com/helm/charts/issues/7726
  #       revision: {{ .Release.Revision | quote }}
  #   spec:
  #     accessModes: [ "ReadWriteOnce" ]
  #     resources:
  #       requests:
  #         storage: 50Mi
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "notification-service.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ include "notification-service.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}