kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: transaction-processing
  name: namespace-reader
rules:
  - apiGroups: [""]
    resources: ["configmaps", "pods", "services", "endpoints", "secrets"]
    verbs: ["get", "list", "watch"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: namespace-reader-binding
  namespace: transaction-processing
subjects:
- kind: ServiceAccount
  name: notification-service
  apiGroup: ""
roleRef:
  kind: Role
  name: namespace-reader
  apiGroup: ""
